### ISSUE TITLE
Retrieving screenshots from player

### ISSUE THREAD

**Issue by ilyai** [OutOfAxis/pixelart-player-bs#9]
BrightSign API has support for getting screenshots: http://docs.brightsign.biz/display/DOC/roVideoMode#roVideoMode-Screenshot(parametersAsroAssociativeArray)AsBoolean
And we're interested to have that functionality in our CMS.

There's also a topic on forum containing more details: https://brightsign.zendesk.com/hc/en-us/community/posts/209965637-roVideoMode-Screenshot-documentation

**Comment by BartoszPOL** [comment]
It's handled in BRS
